# Generated by Django 4.2.17 on 2026-04-04 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("course", models.CharField(max_length=50)),
                ("start_time", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("qb_url", models.URLField(max_length=500)),
                ("questions_json", models.JSONField(blank=True, null=True)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                (
                    "marking_scheme",
                    models.CharField(
                        choices=[
                            (
                                "neet_pg",
                                "NEET PG (+4 correct / -1 incorrect / 0 skipped)",
                            ),
                            ("usmle", "USMLE (+1 correct / 0 incorrect / 0 skipped)"),
                            (
                                "positive_only",
                                "Positive Only (+1 correct / 0 incorrect / 0 skipped)",
                            ),
                        ],
                        default="neet_pg",
                        max_length=20,
                    ),
                ),
                ("answer_key_json", models.JSONField(blank=True, default=dict)),
                (
                    "leaderboard_cache_payload",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "leaderboard_cache_computed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ContestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="contest.contest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "contest")},
            },
        ),
        migrations.CreateModel(
            name="ContestQuestionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("question_id", models.CharField(max_length=100)),
                ("selected_options", models.JSONField(blank=True, null=True)),
                ("is_skipped", models.BooleanField(default=False)),
                (
                    "contest_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="contest.contestattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("contest_attempt", "question_id")},
            },
        ),
    ]
