services:
  redis:
    image: redis
    volumes:
      - "./redis-data:/data"
    command: redis-server --appendonly yes
    restart: on-failure

  api:
    build:
      context: .
    working_dir: /usr/src/app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env
    environment:
      REDIS_HOST: redis
      WATCHFILES_FORCE_POLLING: "true"
    depends_on:
      - redis
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./dev_conf.d/:/etc/nginx/conf.d/
      - /var/log/nginx/:/var/log/nginx/
      - django_admin_static_files:/home/app/static

volumes:
  django_admin_static_files:
