services:
  redis:
    image: redis
    volumes:
      - "./redis-data:/data"
    command: redis-server --appendonly yes
    restart: on-failure
    ports:
      - "6379:6379"
  api:
    build:
      context: ./backend/
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput &&  python manage.py create_theme && daphne -b 0.0.0.0 -p 8000 backend.asgi:application"
    volumes:
      - ./backend/:/usr/src/app/backend/
    env_file:
      - ./backend/dev.env
    expose:
      - 8000

  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./dev_conf.d/:/etc/nginx/conf.d/
      - /var/log/nginx/:/var/log/nginx/
      - django_admin_static_files:/home/app/backend/static

volumes:
  django_admin_static_files:
