export const SAMPLE_QUESTIONS = [
  { question: "What are common symptoms of the flu?", emoji: "🤒" },
  { question: "How can I reduce my cholesterol levels naturally?", emoji: "🍎" },
  { question: "What foods are high in iron?", emoji: "🥩" },
  { question: "Why do I get headaches frequently?", emoji: "🤕" },
  { question: "What are the causes of high blood pressure?", emoji: "💉" },
  { question: "How much water should I drink daily?", emoji: "💧" },
  { question: "What are some tips for better sleep?", emoji: "😴" },
  { question: "Is intermittent fasting safe for everyone?", emoji: "⏳" },
  { question: "What is a balanced diet?", emoji: "🥗" },
  { question: "What are common allergies?", emoji: "🌿" },
  { question: "How often should I exercise?", emoji: "🏋️‍♂️" },
  { question: "What are some stress management techniques?", emoji: "😌" },
  { question: "How can I improve my mental health?", emoji: "🧠" },
  { question: "What foods are good for the heart?", emoji: "❤️" },
  { question: "How can I prevent colds?", emoji: "🤧" },
  { question: "What causes insomnia?", emoji: "🌙" },
  { question: "What are the benefits of vitamin C?", emoji: "🍊" },
  { question: "How can I build stronger bones?", emoji: "🦴" },
  { question: "What is a good daily calorie intake?", emoji: "⚖️" },
  { question: "What are early signs of diabetes?", emoji: "🍬" },
  { question: "How can I increase my energy levels?", emoji: "⚡" },
  { question: "What is a migraine?", emoji: "💆" },
  { question: "How does anxiety affect health?", emoji: "😟" },
  { question: "What are common symptoms of COVID-19?", emoji: "🦠" },
  { question: "How can I improve my digestion?", emoji: "🥬" },
  { question: "What is mindful eating?", emoji: "🍽️" },
  { question: "How does hydration affect my skin?", emoji: "💦" },
  { question: "What are natural ways to boost immunity?", emoji: "🌿" },
  { question: "What is sleep apnea?", emoji: "🛌" },
  { question: "How can I quit smoking?", emoji: "🚬" },
  { question: "What foods should I avoid during pregnancy?", emoji: "🤰" },
  { question: "How do I know if I have allergies?", emoji: "🤧" },
  { question: "What causes muscle cramps?", emoji: "💪" },
  { question: "How does sugar affect my health?", emoji: "🍬" },
  { question: "What are healthy snacks?", emoji: "🍏" },
  { question: "What is high cholesterol?", emoji: "🩸" },
  { question: "How can I reduce belly fat?", emoji: "🏃‍♀️" },
  { question: "What is the DASH diet?", emoji: "🥕" },
  { question: "What causes back pain?", emoji: "🔙" },
  { question: "How does exercise improve mood?", emoji: "😊" },
  { question: "What is the role of protein in my diet?", emoji: "🍗" },
  { question: "What is a panic attack?", emoji: "😱" },
  { question: "What foods are good for brain health?", emoji: "🧠" },
  { question: "How can I reduce joint pain?", emoji: "🦵" },
  { question: "What are the benefits of yoga?", emoji: "🧘" },
  { question: "What is seasonal affective disorder?", emoji: "🌧️" },
  { question: "How can I reduce sugar intake?", emoji: "🚫🍭" },
  { question: "What is a healthy BMI?", emoji: "⚖️" },
  { question: "How does caffeine affect my body?", emoji: "☕" },
  { question: "How can I manage stress at work?", emoji: "💼" },
  { question: "What are probiotics?", emoji: "🦠" },
  { question: "How does lack of sleep affect health?", emoji: "🛌" },
  { question: "What are superfoods?", emoji: "🥑" },
  { question: "How does alcohol impact health?", emoji: "🍷" },
  { question: "What are common symptoms of depression?", emoji: "😔" },
  { question: "What are tips for healthy skin?", emoji: "💆‍♀️" },
  { question: "What is cholesterol?", emoji: "💉" },
  { question: "What are healthy sources of carbs?", emoji: "🍞" },
  { question: "How can I lower my blood sugar?", emoji: "📉" },
  { question: "What causes tooth decay?", emoji: "🦷" },
  { question: "What foods are good for the liver?", emoji: "🥦" },
  { question: "How can I prevent osteoporosis?", emoji: "🦴" },
  { question: "What is a balanced workout routine?", emoji: "🏋️" },
  { question: "What is meditation?", emoji: "🧘‍♂️" },
  { question: "What causes indigestion?", emoji: "😖" },
  { question: "How can I prevent skin aging?", emoji: "👵" },
  { question: "What are the benefits of green tea?", emoji: "🍵" },
  { question: "What is mental health?", emoji: "🧠" },
  { question: "How does sitting affect my health?", emoji: "💺" },
  { question: "What causes fatigue?", emoji: "😴" },
  { question: "What is inflammation?", emoji: "🔥" },
  { question: "What are the symptoms of a UTI?", emoji: "🚽" },
  { question: "How can I boost my metabolism?", emoji: "🔥" },
  { question: "What is fiber and why is it important?", emoji: "🌾" },
  { question: "How can I reduce stress naturally?", emoji: "🍃" },
  { question: "What foods support weight loss?", emoji: "🥗" },
  { question: "How can I improve my posture?", emoji: "🧍" },
  { question: "What are antioxidants?", emoji: "🍇" },
  { question: "How does diet impact mental health?", emoji: "🍉" },
  { question: "What are good sources of vitamin D?", emoji: "☀️" },
  { question: "What is the keto diet?", emoji: "🥓" },
  { question: "What are symptoms of gluten intolerance?", emoji: "🌾" },
  { question: "How can I protect my vision?", emoji: "👓" },
  { question: "What is muscle soreness?", emoji: "💪" },
  { question: "What causes bloating?", emoji: "😣" },
  { question: "What is the importance of sleep?", emoji: "🛌" },
  { question: "What is a healthy heart rate?", emoji: "❤️" },
  { question: "How can I control food cravings?", emoji: "🍫" },
  { question: "What is hydration?", emoji: "💧" },
  { question: "What are the benefits of fish oil?", emoji: "🐟" },
  { question: "What is osteoporosis?", emoji: "🦴" },
  { question: "How can I keep my teeth healthy?", emoji: "🦷" },
  { question: "What is considered normal blood pressure?", emoji: "📉" },
  { question: "What is adrenal fatigue?", emoji: "😴" },
  { question: "How does screen time affect health?", emoji: "📱" },
  { question: "What are health risks of obesity?", emoji: "⚠️" },
  { question: "How does exercise affect the brain?", emoji: "🏃" },
  { question: "What are the symptoms of a heart attack?", emoji: "💔" },
];
