import { ILayoutProps } from "@/models";
import { LandingPageHeader } from "./_components";
import Footer from "./_components/footer";
import "./global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: ILayoutProps) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <LandingPageHeader />
        {props.children}
        <Footer />
      </body>
    </html>
  );
}
