# Generated by Django 4.2.17 on 2026-04-04 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.CharField(db_index=True, max_length=50)),
                ("subject", models.CharField(db_index=True, max_length=100)),
                ("module", models.CharField(db_index=True, max_length=100)),
                ("question_id", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "course"], name="practice_qu_user_id_779aab_idx"
                    ),
                    models.Index(
                        fields=["user", "subject"],
                        name="practice_qu_user_id_b44ee9_idx",
                    ),
                    models.Index(
                        fields=["user", "module"], name="practice_qu_user_id_bb3643_idx"
                    ),
                ],
                "unique_together": {
                    ("user", "course", "subject", "module", "question_id")
                },
            },
        ),
    ]
