# Generated by Django 4.2.17 on 2026-04-18 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPracticePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("monthly", "Pro monthly"),
                            ("annual", "Pro annual"),
                            ("lifetime", "Lifetime"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the paid period starts. Expiry is computed from this and the plan when saved.",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Computed from Started at and plan when the row is saved. Not editable.",
                        null=True,
                    ),
                ),
                (
                    "is_lifetime",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        help_text="Set automatically from plan (true only for lifetime). Not editable.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Exactly one row per user may be active. Saving with active=True deactivates other rows for this user.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="practice_us_expires_f4f1de_idx"
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="practice_us_user_id_6e20cc_idx",
                    ),
                ],
            },
        ),
    ]
