# Generated by Django 4.1.1 on 2024-10-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
