# Generated by Django 4.1.1 on 2024-10-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="conditions_treated",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="insurance_accepted",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="procedures_performed",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="specialties",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="overview",
            field=models.TextField(blank=True, null=True),
        ),
    ]
